<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ManagerRcon</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(LoaderPath)/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim"><HintPath>$(GameManagedPath)/assembly_valheim.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_utils"><HintPath>$(GameManagedPath)/assembly_utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Splatform"><HintPath>$(GameManagedPath)/Splatform.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(GameManagedPath)/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.JSONSerializeModule"><HintPath>$(GameManagedPath)/UnityEngine.JSONSerializeModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManagedPath)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
